dist: trusty
sudo: false
language: node_js
node_js:
    - "node"
services:
    - xvfb
cache:
    directories:
        - "node_modules"
matrix:
    include:
        - addons:
            chrome: stable
          env: TEST_CHROME="1"
          # Work-around for https://github.com/travis-ci/travis-ci/issues/8836
          sudo: required
        - addons:
            firefox: latest-unsigned
          env: TEST_FX="1"
notifications:
    email: false
script:
    - ./test/run_tests