#!/bin/bash
set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$( cd "$DIR"/../.. && pwd )"

. "$ROOT_DIR/config.sh"

channel=${1:-release}

# Use JM node deployer
DEPLOYER_CHANNEL_TAG="${DEPLOYER_TOP_TAG}/firefox/$channel"

RET=$(node "$ROOT_DIR/deployer/index.js" -q -d "${DEPLOYER_CHANNEL_TAG}/updates.json" | jq -r '.addons["jurism@juris-m.github.io"].updates[-1].version')

if [ "$RET" == "" ]; then 
    echo "null"
else
    echo "$RET"
fi
 
