#!/bin/bash
set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$( cd "$DIR"/../.. && pwd )"

. "$ROOT_DIR/config.sh"

function usage {
	echo "Usage: $0 CHANNEL VERSION" >&2
	exit 1
}

if [[ -z "${1:-}" ]] || [[ -z "${2:-}" ]]; then
	usage
fi

channel=$1
version=$2

DEPLOYER_TAG=${DEPLOYER_UPDATE_TAG/CHANNEL/$channel}
node "$ROOT_DIR/deployer/index.js" -q -d "${DEPLOYER_TAG}lastrev-$version" || echo -n 0
