#!/bin/bash -eu

#
# Upload signed XPI to GitHub with correct content type
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$( cd "$DIR"/../.. && pwd )"
BUILD_DIR="$( cd "$DIR"/../../build && pwd )"

. "$ROOT_DIR/config.sh"

channel=${1:-}
if [ -z "$channel" ]; then
	echo "Usage: $0 CHANNEL" >&2
	exit 1
fi

XPI="`$DIR/get_xpi_path`"
VERSION="$( unzip -p "$XPI" manifest.json | jq -r .version )"

if ! unzip -l "$XPI" | grep --quiet META-INF; then
	echo "$XPI is not signed"
	exit 1
fi

DEPLOYER_CHANNEL_TAG="${DEPLOYER_TOP_TAG}/firefox/$channel"
node "$ROOT_DIR/deployer/index.js" -t "application/x-xpinstall" -u "$XPI" "${DEPLOYER_CHANNEL_TAG}/Jurism_Connector-$VERSION.xpi"

rm $XPI
